import { existsSync, writeFileSync, readFileSync, mkdirSync } from 'fs';
import { resolve, basename, dirname } from 'path';
import { execSync } from 'child_process';
import { homedir } from 'os';

// ── Types ──

export interface OrchRole {
  name: string;
  tier: 1 | 2 | 3;
  description: string;
}

export interface OrchInitOptions {
  name?: string;
  force?: boolean;
  dryRun?: boolean;
}

export interface OrchInitResult {
  step: string;
  status: 'ok' | 'skipped' | 'error' | 'would_execute';
  detail?: string;
}

// ── ORCH roles ──

const ORCH_ROLES: OrchRole[] = [
  {
    name: 'Arch',
    tier: 1,
    description:
      'Architect — strategic design, task decomposition, system planning (at tier 1)',
  },
  {
    name: 'Dev',
    tier: 2,
    description:
      'Developer — feature implementation, bug fixes, code generation (at tier 2)',
  },
  {
    name: 'QA',
    tier: 2,
    description:
      'QA — testing, validation, linting, quality assurance (at tier 2)',
  },
  {
    name: 'Reviewer',
    tier: 1,
    description:
      'Reviewer — code review, security audit, best practices (at tier 1)',
  },
];

// ── ORCH helpers ──

function findOrchBin(): string {
  const orchBin = process.env.ORCH_BIN;
  if (orchBin && existsSync(orchBin)) return orchBin;

  const nvmBin = `${dirname(process.execPath)}/orch`;
  if (existsSync(nvmBin)) return nvmBin;

  try {
    const which = execSync('which orch', { encoding: 'utf8', stdio: 'pipe' }).trim();
    if (which) return which;
  } catch {
    // not in PATH
  }

  return 'orch';
}

function orchExec(
  args: string[],
  cwd?: string,
): { stdout: string; stderr: string; status: number } {
  const bin = findOrchBin();
  const cmd = [bin, ...args].map((a) => `'${a.replace(/'/g, "'\\''")}'`).join(' ');
  try {
    const result = execSync(cmd, {
      encoding: 'utf8',
      stdio: 'pipe',
      cwd,
      timeout: 30000,
    });
    return { stdout: result, stderr: '', status: 0 };
  } catch (err: unknown) {
    const e = err as { stdout?: Buffer | string; stderr?: Buffer | string; message: string; status?: number };
    return {
      stdout: typeof e.stdout === 'string' ? e.stdout : (e.stdout?.toString() ?? ''),
      stderr: typeof e.stderr === 'string' ? e.stderr : (e.stderr?.toString() ?? e.message),
      status: e.status ?? 1,
    };
  }
}

function wrapperScript(role: OrchRole): string {
  return `#!/bin/bash
# ORCH shell agent: ${role.name} — delegates to at (tier ${role.tier})
# Generated by: at init
set -e
: "\${ORCHESTRY_TASK_PROMPT:?ORCHESTRY_TASK_PROMPT not set}"
printf '%s' "$ORCHESTRY_TASK_PROMPT" | at -t ${role.tier}
`;
}

function existingOrchAgentNames(): string[] {
  const indexPath = '.orchestry/agents/_index.json';
  if (!existsSync(indexPath)) return [];
  try {
    const index = JSON.parse(readFileSync(indexPath, 'utf8'));
    return index.map((a: { name: string }) => a.name.toLowerCase());
  } catch {
    return [];
  }
}

// ── ORCH init entry point ──

export function runOrchInit(options: OrchInitOptions = {}): OrchInitResult[] {
  const results: OrchInitResult[] = [];
  const projectName = options.name ?? basename(process.cwd());
  const orchDir = '.orchestry';
  const wrappersDir = `${orchDir}/wrappers`;

  // ── Step 1: check orch binary ──
  const orchBin = findOrchBin();
  try {
    execSync(`"${orchBin}" --version`, { encoding: 'utf8', stdio: 'pipe' });
    results.push({ step: 'check orch', status: 'ok', detail: orchBin });
  } catch {
    results.push({
      step: 'check orch',
      status: 'error',
      detail:
        `orch not found at "${orchBin}". ` +
        'Install with: npm i -g @oxgeneral/orch',
    });
    return results;
  }

  // ── Step 2: orch init ──
  if (!existsSync(orchDir)) {
    if (options.dryRun) {
      results.push({
        step: 'orch init',
        status: 'would_execute',
        detail: `orch init --name "${projectName}"`,
      });
    } else {
      const r = orchExec(['init', '--name', projectName]);
      if (r.status !== 0) {
        results.push({
          step: 'orch init',
          status: 'error',
          detail: r.stderr || r.stdout || 'unknown error',
        });
        return results;
      }
      results.push({
        step: 'orch init',
        status: 'ok',
        detail: `.orchestry/ initialized for "${projectName}"`,
      });
    }
  } else {
    results.push({
      step: 'orch init',
      status: 'skipped',
      detail: '.orchestry/ already exists',
    });
  }

  // ── Step 3: create wrapper scripts ──
  if (!options.dryRun && !existsSync(wrappersDir)) {
    mkdirSync(wrappersDir, { recursive: true });
  }

  for (const role of ORCH_ROLES) {
    const wrapperPath = `${wrappersDir}/orch-${role.name.toLowerCase()}.sh`;

    if (existsSync(wrapperPath) && !options.force) {
      results.push({
        step: `wrapper: ${role.name}`,
        status: 'skipped',
        detail: `${wrapperPath} already exists (use --force to overwrite)`,
      });
      continue;
    }

    if (options.dryRun) {
      results.push({
        step: `wrapper: ${role.name}`,
        status: 'would_execute',
        detail: `would create ${wrapperPath}`,
      });
      continue;
    }

    writeFileSync(wrapperPath, wrapperScript(role), { mode: 0o755 });
    results.push({
      step: `wrapper: ${role.name}`,
      status: 'ok',
      detail: wrapperPath,
    });
  }

  // ── Step 4: create ORCH agents ──
  if (!options.dryRun && existsSync(orchDir)) {
    const existing = existingOrchAgentNames();

    for (const role of ORCH_ROLES) {
      const nameLower = role.name.toLowerCase();
      if (existing.includes(nameLower)) {
        results.push({
          step: `agent: ${role.name}`,
          status: 'skipped',
          detail: 'already registered in .orchestry/',
        });
        continue;
      }

      const wrapperPath = resolve(wrappersDir, `orch-${nameLower}.sh`);
      const r = orchExec([
        'agent', 'add', role.name,
        '--adapter', 'shell',
        '--role', role.description,
        '--command', wrapperPath,
        '--approval-policy', 'auto',
        '--timeout', '600000',
      ]);

      if (r.status !== 0) {
        results.push({
          step: `agent: ${role.name}`,
          status: 'error',
          detail: r.stderr || r.stdout || 'orch agent add failed',
        });
      } else {
        results.push({
          step: `agent: ${role.name}`,
          status: 'ok',
          detail: `shell adapter → at tier ${role.tier} (${wrapperPath})`,
        });
      }
    }
  }

  return results;
}

export function formatOrchInitResults(results: OrchInitResult[]): string {
  if (results.length === 0) return 'Nothing to do.';

  return results
    .map((r) => {
      const icon =
        r.status === 'ok'
          ? '✓'
          : r.status === 'skipped'
            ? '○'
            : r.status === 'error'
              ? '✗'
              : '→';
      const detail = r.detail ? ` — ${r.detail}` : '';
      return `  ${icon} ${r.step}${detail}`;
    })
    .join('\n');
}
